# Generated by Django 6.0.5 on 2026-06-11 18:10

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_author_article_body_article_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('animal_type', models.CharField(choices=[('Mol', "Mol go'shti"), ("Qo'y", "Qo'y go'shti"), ('Tovuq', "Tovuq go'shti"), ('Boshqa', 'Boshqa mahsulotlar')], default='Mol', max_length=50, verbose_name='Hayvon turi')),
                ('cut_type', models.CharField(max_length=100, verbose_name="Go'sht bo'lagi (Laxm, Qovurg'a, To'sh va h.k.)")),
                ('price', models.IntegerField(verbose_name="Narxi (1 kg uchun so'mda)")),
                ('stock_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ombordagi qoldiq (kg)')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Mahsulot ta'rifi")),
                ('photo', models.ImageField(blank=True, upload_to='products/', verbose_name='Asosiy rasm')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim")),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.product')),
            ],
        ),
    ]
