# Generated by Django 6.0.5 on 2026-06-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_author_remove_articleimage_article_and_more'),
        ('comments', '0003_remove_comment_article_comment_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
