# Generated by Django 6.0.5 on 2026-06-24 08:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Mijoz ismi')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiyasi')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('custom_id', models.CharField(max_length=50, unique=True, verbose_name='Mijoz ID')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='Bonus ballari')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Qarz miqdori (so'm)")),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name="Qora ro'yxatdami?")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Eslatma/Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Chakana narxi (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Sotuvda bormi?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Mahsulot rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ta'minotchi ismi")),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiyasi')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('custom_id', models.CharField(max_length=50, unique=True, verbose_name="Ta'minotchi ID")),
                ('our_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Bizning qarzimiz (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('sale', 'Xarid'), ('debt_add', "Qarz ko'payishi"), ('debt_pay', "Qarz to'lashi"), ('bonus', "Bonus o'zgarishi")], max_length=20, verbose_name='Amal turi')),
                ('title', models.CharField(max_length=255, verbose_name='Amal sarlavhasi')),
                ('details', models.JSONField(verbose_name="Tizimli batafsil ma'lumotlar (JSON)")),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amal summasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pos.customer', verbose_name='Mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Asl hisoblangan summa')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="O'tib berilgan chegirma")),
                ('bonus_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Bonusdan yechilgan summa')),
                ('debt_added', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Qarzga yozilgan summa')),
                ('final_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amalda to'langan summa")),
                ('payment_method', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Plastik Karta'), ('qr', 'TBC QR'), ('nasiya', 'Nasiya (Qarz)')], default='naqd', max_length=10, verbose_name="To'lov turi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Savdo vaqti')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.customer', verbose_name='Xaridor')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Vazni/Soni')),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sotilgan vaqtdagi narxi')),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oraliq summa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Zaxira (kg/dona)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='Slaughter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('mol', 'Qora mol'), ('qoy', "Qo'y")], max_length=10, verbose_name='Hayvon turi')),
                ('total_weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Toza go'sht og'irligi (kg)")),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Xarid narxi (so'm/kg)")),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami xarid summasi')),
                ('due_date', models.DateField(verbose_name="To'lov muddati (Nasiya)")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'landimi?")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="So'yilgan vaqti")),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slaughters', to='pos.supplier', verbose_name="Ta'minotchi")),
            ],
        ),
    ]
