# Generated by Django 6.0.5 on 2026-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='Mijoz rasmi'),
        ),
        migrations.AddField(
            model_name='customerlog',
            name='message',
            field=models.TextField(default='', verbose_name='Batafsil matn (Chat xabari)'),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name="Tizimli batafsil ma'lumotlar (JSON)"),
        ),
    ]
