# Generated by Django 6.0.5 on 2026-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_customer_image_customerlog_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Daftar nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
