# Generated by Django 6.0.5 on 2026-06-30 17:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_notebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Dastlabki og'irligi (kg)")),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Joriy og'irligi (kg)")),
                ('purchase_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Xarid narxi (so'm/kg)")),
                ('decay_rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Kunlik qurish zarari (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pos.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
