# Generated by Django 6.0.5 on 2026-06-30 18:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=12, verbose_name="Kredit qarz limiti (so'm)"),
        ),
    ]
