# Generated by Django 6.0.5 on 2026-07-03 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_customer_debt_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'Kirim (Cash In)'), ('out', 'Chiqim (Cash Out)')], max_length=5, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('category', models.CharField(choices=[('kassa_float', "Kassa boshlang'ich qoldig'i"), ('expense', 'Xarajat / Chiqim'), ('supplier_pay', "Ta'minotchiga to'lov"), ('salary', "Ish haqi to'lovi"), ('debt_pay', "Qarz to'lovi (Mijoz)"), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('payment_method', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Plastik karta')], default='naqd', max_length=10, verbose_name="To'lov turi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh / Maqsad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul")),
            ],
        ),
    ]
