# Generated by Django 6.0.5 on 2026-07-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_slaughter_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Kutilayotgan og'irlik (kg)")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Maxsus eslatmalar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('completed', 'Yakunlandi')], default='pending', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_orders', to='pos.customer', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_orders', to='pos.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
