# Generated by Django 6.0.5 on 2026-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_b2border'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Eslatma/Izoh'),
        ),
    ]
