# Generated by Django 6.0.5 on 2026-07-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_supplier_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.customer', verbose_name='Mijoz (Xaridor)'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.supplier', verbose_name="Ta'minotchi"),
        ),
    ]
