# Generated by Django 6.0.5 on 2026-07-10 08:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='slaughter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_sold', to='pos.slaughter', verbose_name="So'yim partiyasi"),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='stock_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_sold', to='pos.stockbatch', verbose_name="Tayyor go'sht partiyasi"),
        ),
        migrations.AddField(
            model_name='slaughter',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Qolgan vazn (kg)'),
        ),
        migrations.AddField(
            model_name='slaughter',
            name='status',
            field=models.CharField(choices=[('active', 'Sotilmoqda'), ('completed', 'Sotib tugatildi')], default='active', max_length=15, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to='pos.customer', verbose_name='Mijoz profili'),
        ),
    ]
