# Generated by Django 6.0.5 on 2026-07-13 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_saleitem_slaughter_saleitem_stock_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_proofs/', verbose_name='Chek rasmi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('provider', models.CharField(default='karta', max_length=20, verbose_name="To'lov tizimi")),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Admin tasdiqladi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='pos.customer', verbose_name='Mijoz')),
                ('customer_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof', to='pos.customerlog', verbose_name="Bog'liq log")),
            ],
        ),
    ]
