# Generated by Django 6.0.5 on 2026-07-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_add_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deduct_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_products', to='pos.product', verbose_name='Zaxira qaysi mahsulotdan ayriladi?'),
        ),
    ]
