# Generated by Django 6.0.5 on 2026-07-16 15:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_product_deduct_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Shift ochilgan vaqt')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Shift yopilgan vaqt')),
                ('is_open', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Boshlang'ich naqd pul (so'm)")),
                ('closed_cash_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Kutilayotgan naqd pul (so'm)")),
                ('closed_cash_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Faktik naqd pul (so'm)")),
                ('closed_card_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Kutilayotgan karta (so'm)")),
                ('closed_debt_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Kutilayotgan nasiya (so'm)")),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Farq (so'm)")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Shift izohi')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.cashiershift', verbose_name='Kassa shifti'),
        ),
    ]
