# Generated by Django 6.0.7 on 2026-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_cashiershift_sale_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
