# Generated by Django 6.0.7 on 2026-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_customer_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2border',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Yetkazish manzili'),
        ),
        migrations.AddField(
            model_name='b2border',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Dostavka (Yetkazib berish)'), ('pickup', "Samovivoz (Do'kondan olib ketish)")], default='delivery', max_length=20, verbose_name='Yetkazib berish turi'),
        ),
        migrations.AddField(
            model_name='b2border',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='b2border',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AddField(
            model_name='b2border',
            name='payment_method',
            field=models.CharField(choices=[('karta', 'Karta (Click / Payme)'), ('naqd', 'Naqd (Qabul qilganda)'), ('nasiya', 'Nasiya')], default='karta', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='b2border',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name="To'lov cheki fotosi"),
        ),
        migrations.AlterField(
            model_name='b2border',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda (Chek kutilmoqda)'), ('payment_uploaded', "To'lov cheki yuklandi"), ('approved', 'Tasdiqlandi'), ('preparing', "Go'sht tortilmoqda/Qadoqlanmoqda"), ('shipping', "Kuryer yo'lda"), ('completed', 'Muvaffaqiyatli yetkazildi'), ('rejected', 'Rad etildi')], default='pending', max_length=25, verbose_name='Status'),
        ),
    ]
