# Generated by Django 6.0.7 on 2026-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_b2border_delivery_address_b2border_delivery_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Click / Payme / Karta', max_length=100, verbose_name="To'lov tizimi nomi")),
                ('card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Karta raqami (masalan: 8600 1234 5678 9012)')),
                ('card_holder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Karta egasi F.I.SH')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR kod fotosi')),
                ('instructions', models.TextField(blank=True, default="To'lovni amalga oshirgach, to'lov cheki fotosini ushbu chatga yuboring.", null=True, verbose_name="Mijozga yo'riqnoma")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "To'lov Rekviziti (Karta/QR)",
                'verbose_name_plural': "To'lov Rekvizitlari (Karta/QR)",
            },
        ),
    ]
