# Generated by Django 6.0.4 on 2026-07-25 15:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_paymentsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Baxmal Meat Do'koni", max_length=100, verbose_name="Do'kon nomi")),
                ('address', models.CharField(default='Toshkent shahri, Chilonzor tuman', max_length=255, verbose_name="Do'kon manzili")),
                ('latitude', models.FloatField(default=41.2995, verbose_name="Do'kon GPS Latitude")),
                ('longitude', models.FloatField(default=69.2401, verbose_name="Do'kon GPS Longitude")),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name="Boshlang'ich kuryer narxi (so'm)")),
                ('fee_per_km', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), max_digits=10, verbose_name="Har bir km uchun (so'm)")),
                ('min_free_delivery_amount', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12, verbose_name="Bepul yetkazish minimal summasi (so'm)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Do'kon Sozlamasi & Lokatsiyasi",
                'verbose_name_plural': "Do'kon Sozlamalari & Lokatsiyasi",
            },
        ),
        migrations.AddField(
            model_name='b2border',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='pos.customer', verbose_name='Biriktirilgan Kuryer'),
        ),
        migrations.AddField(
            model_name='b2border',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Kuryerlik (Dostavka) haqsi'),
        ),
        migrations.AddField(
            model_name='b2border',
            name='distance_km',
            field=models.FloatField(default=0.0, verbose_name='Masofa (km)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='courier_status',
            field=models.CharField(choices=[('none', 'Mijoz'), ('pending', 'Kuryerlikka ariza bergan'), ('approved', 'Tasdiqlangan Kuryer'), ('rejected', 'Rad etilgan')], default='none', max_length=20, verbose_name='Kuryerlik statusi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='courier_vehicle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transport turi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_courier',
            field=models.BooleanField(default=False, verbose_name='Kuryermi?'),
        ),
    ]
