# Generated by Django 6.0.4 on 2026-08-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_storesetting_b2border_assigned_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='announcement_text',
            field=models.CharField(default="🔥 Mol va Qo'y go'shtidan buyurtma bering — Toshkent bo'ylab yetkazib berish va halol kafolat!", max_length=255, verbose_name="Yuqori e'lon matni"),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='hero_subtitle',
            field=models.TextField(default='Baxmal Meat — Fermadan dasturxongacha laboratoriya nazorati, IoT smart tarozilar, shaffof hisob-kitob va tezkor kuryerlik xizmati.', verbose_name="Bosh sahifa ta'rifi (Hero Subtitle)"),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='hero_title',
            field=models.CharField(default="Sarxil Go'sht & Raqamli MeatFlow Pro Texnologiyasi", max_length=255, verbose_name='Bosh sahifa sarlavhasi (Hero Title)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='phone_number',
            field=models.CharField(default='+998 77 082 4477', max_length=30, verbose_name='Telefon raqam'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='promo_banner_text',
            field=models.CharField(default="500,000 so'mdan yuqori buyurtmalar uchun Toshkent shahri bo'ylab yetkazib berish BEPUL!", max_length=255, verbose_name='Aksiya banneri matni'),
        ),
    ]
