# Generated by Django 6.0.7 on 2026-08-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_storesetting_announcement_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='promo_active',
            field=models.BooleanField(default=True, verbose_name='Aksiya Banneri Faolmi?'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='promo_badge_text',
            field=models.CharField(default='🔥 KATTA AKSIYA', max_length=100, verbose_name='Aksiya Nishoni (Badge)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='promo_image',
            field=models.ImageField(blank=True, null=True, upload_to='promos/', verbose_name='Aksiya 3D Rasmi/Banneri'),
        ),
    ]
