# Generated by Django 6.0.7 on 2026-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_storesetting_promo_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughter',
            name='live_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name="Tirik og'irlik (kg)"),
        ),
    ]
