# Generated by Django 6.0.7 on 2026-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_slaughter_live_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2border',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='b2border',
            name='delivery_type',
            field=models.CharField(choices=[('delivery', 'Dostavka (Yetkazib berish)'), ('pickup', "Samovivoz (Do'kondan olib ketish)")], db_index=True, default='delivery', max_length=20, verbose_name='Yetkazib berish turi'),
        ),
        migrations.AlterField(
            model_name='b2border',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda (Chek kutilmoqda)'), ('payment_uploaded', "To'lov cheki yuklandi"), ('approved', 'Tasdiqlandi'), ('preparing', "Go'sht tortilmoqda/Qadoqlanmoqda"), ('shipping', "Kuryer yo'lda"), ('completed', 'Muvaffaqiyatli yetkazildi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Shift ochilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='category',
            field=models.CharField(choices=[('kassa_float', "Kassa boshlang'ich qoldig'i"), ('expense', 'Xarajat / Chiqim'), ('supplier_pay', "Ta'minotchiga to'lov"), ('salary', "Ish haqi to'lovi"), ('debt_pay', "Qarz to'lovi (Mijoz)"), ('other', 'Boshqa')], db_index=True, default='other', max_length=20, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Kirim (Cash In)'), ('out', 'Chiqim (Cash Out)')], db_index=True, max_length=5, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_blacklisted',
            field=models.BooleanField(db_index=True, default=False, verbose_name="Qora ro'yxatdami?"),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti'),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='log_type',
            field=models.CharField(choices=[('sale', 'Xarid'), ('debt_add', "Qarz ko'payishi"), ('debt_pay', "Qarz to'lashi"), ('bonus', "Bonus o'zgarishi")], db_index=True, max_length=20, verbose_name='Amal turi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Sotuvda bormi?'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Savdo vaqti'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Plastik Karta'), ('qr', 'TBC QR'), ('nasiya', 'Nasiya (Qarz)')], db_index=True, default='naqd', max_length=10, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='slaughter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="So'yilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='slaughter',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, verbose_name="To'landimi?"),
        ),
        migrations.AlterField(
            model_name='slaughter',
            name='status',
            field=models.CharField(choices=[('active', 'Sotilmoqda'), ('completed', 'Sotib tugatildi')], db_index=True, default='active', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Kiritilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Qo'shilgan vaqti"),
        ),
    ]
