# Generated by Django 6.0.7 on 2026-08-14 05:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_alter_b2border_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='cashback_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4, verbose_name='Mijoz Keshbek foizi (%)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='send_sms_receipts',
            field=models.BooleanField(default=True, verbose_name='SMS Chek yuborish faolmi?'),
        ),
    ]
