# Generated by Django 5.2.17 on 2026-08-19 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_storesetting_cashback_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='pos.supplier', verbose_name="Ta'minotchi"),
        ),
    ]
