# Generated by Django 6.0.7 on 2026-08-22 09:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_alter_cashtransaction_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_karta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Karta to'langan"),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_naqd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Naqd to'langan"),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_qr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="QR to'langan"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Plastik Karta'), ('qr', 'TBC QR'), ('nasiya', 'Nasiya (Qarz)'), ('aralash', 'Aralash (Split)')], db_index=True, default='naqd', max_length=15, verbose_name="To'lov turi"),
        ),
    ]
