# Generated by Django 6.0.7 on 2026-08-23 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_sale_paid_karta_sale_paid_naqd_sale_paid_qr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Kelishilgan maxsus narx (so'm)")),
                ('notes', models.CharField(blank=True, max_length=150, null=True, verbose_name='Eslatma (masalan: Choyxona narxi)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='pos.customer', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_special_prices', to='pos.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mijoz maxsus narxi',
                'verbose_name_plural': 'Mijozlar maxsus narxlari',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
