# Generated by Django 6.0.7 on 2026-09-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_customerspecialprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True, verbose_name='AI Face ID Vektor (128d)'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='address',
            field=models.CharField(default='Jizzax viloyati, Baxmal tumani, Sangzor Guzari', max_length=255, verbose_name="Do'kon manzili"),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='announcement_text',
            field=models.CharField(default="🔥 Mol va Qo'y go'shtidan buyurtma bering — Halol va sarxil go'sht kafolati!", max_length=255, verbose_name="Yuqori e'lon matni"),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='hero_subtitle',
            field=models.TextField(default='Baxmal Meat — Fermadan dasturxongacha laboratoriya nazorati, IoT smart tarozilar, shaffof hisob-kitob va tezkor xizmat.', verbose_name="Bosh sahifa ta'rifi (Hero Subtitle)"),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='promo_banner_text',
            field=models.CharField(default="Baxmal tumani bo'ylab buyurtmalarni tezkor yetkazib beramiz!", max_length=255, verbose_name='Aksiya banneri matni'),
        ),
    ]
