# Generated by Django 6.0.7 on 2026-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_customer_face_descriptor_alter_storesetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='voice_raw_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ovozli xom matn'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi eslatma yuborilgan vaqt'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Eslatmalar soni'),
        ),
        migrations.AlterField(
            model_name='customerlog',
            name='log_type',
            field=models.CharField(choices=[('sale', 'Xarid'), ('debt_add', "Qarz ko'payishi"), ('debt_pay', "Qarz to'lashi"), ('bonus', "Bonus o'zgarishi"), ('reminder', 'Qarz eslatmasi yuborildi')], db_index=True, max_length=20, verbose_name='Amal turi'),
        ),
    ]
